### PR TITLE
Feature/multiple array suffix

### LINKED ISSUE #31: Nested arrays result in "expected (Ident) got Open Square"
This might be a little tough to solve/the generated code could change a lot if an infinite amount of nesting is allowed.

The TypeScript version of bebop-tools compiles `byte[][][]` in my .bop to `Array<Array<Uint8Array>>`.

And thank you for maintaining this lib!! 😄

### PR DESCRIPTION
**Pull request by 200sc**
This changeset: 
- Adds missing support for field types with multiple `[]` suffixes e.g. `byte[][][] bytes` 
- Updates internal compatibility tests with rainway to 2.4.9. 

Closes #31

### CODE REVIEW

**Comment by merlindru** [comment]
I haven't tested this, but I'd love to see this land! Do you want/need me to test it?

**Comment by merlindru** [comment]
As always, thank you for the incredibly fast turnaround time 😄 And seriously, hats off for maintaining this awesome lib

**Comment by 200sc** [comment]
@merlindru Thanks! Yes, I left it up for you to verify, but if you're happy I'll merge it with a version bump

**Comment by merlindru** [comment]
Give me a minute to test it out

**Comment by merlindru** [comment]
@200sc Tested both `uint8[][][]` and `array[array[array[uint8]]]`, works perfectly fine!

Just for fun, I shoddily tested a nesting of 1024 levels, which resulted in a 20k line file (`ls -lh` reports it as 29M large) and it was still in the single-digit seconds (for both generating and writing to disc)

**Review by merlindru — APPROVED** [review]

**Pull request merged**
